### ISSUE TITLE
是否应该在readme中说明下对于bigint支持的不完善，避免有人踩坑

### ISSUE THREAD

**Issue by nadirvishun** [cloydlau/json-editor-vue#10]
目前有遇到这个问题，如果只读还好点，只是读取错误，如果是编辑那直接就修改源数据了：
- 新版本库中的[issue](https://github.com/josdejong/svelte-jsoneditor/issues/96)，目前作者正在处理中，还未解决。
- 旧版本的库中也有这个问题[issue](https://github.com/josdejong/jsoneditor/issues/231)，这个就有点离谱，2015年的问题到现在都没有关闭。

**Comment by cloydlau** [comment]
这作者不是说有望在两周内解决么：https://github.com/josdejong/svelte-jsoneditor/issues/96#issuecomment-1249248740
如果作者不想解决这个问题，在文档中注明是没问题的，但是既然作者已经表态要解决就没必要了。
而且即使在文档中注明也应该是在 `svelte-jsoneditor` 的文档中，你说对吧。

**Comment by cloydlau** [comment]
`svelte-jsoneditor@0.7.8` 已经支持了。我测试了 `json-editor-vue` 也是支持的，并发布了 `0.7.0` 版本，去掉了 `JSON.stringify` 硬编码的逻辑，以便更好地支持 BigInt。

**Comment by cloydlau** [comment]
已经文档中添加 BigInt 的用法示例
