### ISSUE TITLE
火狐浏览器68版本 无法兼容 报错信息如下

### ISSUE THREAD

**Issue by programmerguohuajing** [cloydlau/json-editor-vue#100]
### Before you start, please make sure to:

- [X] Read the document
- [X] Have tried the latest version
- [X] Search to see if your issue already exists

### Link to minimal reproduction

截图

### Validation

- [X] ⚠️ I understand that invalid, incomplete or superfluous reproduction can lead to this issue being closed

### Describe the bug and steps to reproduce

火狐浏览器68版本 无法兼容
![image](https://github.com/user-attachments/assets/78156478-1cf5-4400-a135-16424803776c)
![cf58862988afa5d324ebded8309bec6e](https://github.com/user-attachments/assets/06dd602f-7981-4e00-9adc-1ead893b30a6)

### Package Manager

npm

**Comment by cloydlau** [comment]
火狐68是2019年推出的版本，Vite 默认也是不支持的（Vite 目前要求至少火狐78）。

提供一个思路供参考，如果还是不行你可以自行调研下并分享下解决方案：

```
npm i -D terser
```

```ts
// vite.config.js
import legacy from '@vitejs/plugin-legacy'

export default {
  optimizeDeps: {
    include: ['json-editor-vue'],
  },
  plugins: [
    legacy({
      targets: ['defaults', 'not IE 11'],
    }),
  ],
}
```

**Comment by programmerguohuajing** [comment]
好的 感谢楼主分享  我试试

**Comment by cloydlau** [comment]
没事，可考虑下点亮 Star 以支持本项目。
