### ISSUE TITLE
Why isn't the font black? It seems like span is missing

### ISSUE THREAD

**Issue by acercom** [cloydlau/json-editor-vue#101]
### Before you start, please make sure to:

- [X] Read the document
- [X] Have tried the latest version
- [X] Search to see if your issue already exists

### Link to minimal reproduction

none

### Validation

- [X] ⚠️ I understand that invalid, incomplete or superfluous reproduction can lead to this issue being closed

### Describe the bug and steps to reproduce

![微信截图_20241202112232](https://github.com/user-attachments/assets/b1d2ee24-dc10-41ff-8675-936ecbb20e0d)

use to 0.17.3 version

### System Info

```shell
use to 0.17.3 version
```

### Package Manager

None

**Comment by cloydlau** [comment]
Unable to reproduce: https://cloydlau.github.io/playground/json-editor-vue/
