### ISSUE TITLE
关于配置v-model:mode为text问题

### ISSUE THREAD

**Issue by comxza** [cloydlau/json-editor-vue#16]
我这边是vue3使用环境  
![image](https://user-images.githubusercontent.com/21981010/196013430-f8d8fc94-b063-4117-a0e9-ac435cc55663.png)
![image](https://user-images.githubusercontent.com/21981010/196013432-9bee0ab6-1160-4b06-8e60-c98c80fea5a7.png)
数据格式为`{
  "bigint": 124124124124124124124,
  "boolean": true,
  "string": "Hello World",
  "number": 123.456,
  "color": "#b0a4e3",
  "null": null,
}`
这样配置后   一直出现如下错误     如果不是配mode为text  那么就是正常的  我想默认为text模式  需要怎么修改呢   
![image](https://user-images.githubusercontent.com/21981010/196013488-ece99259-884f-4058-8a20-7dcb2818a229.png)

**Comment by cloydlau** [comment]
之前有个人提了一样的问题，但我今天再次尝试依然无法复现。能提供一个最小可复现链接吗？（最好是 `codesandbox`）

> [为什么最小可复现链接是必要的](https://antfu.me/posts/why-reproductions-are-required)

另友情提示，如果要使用 bigint，需要配置 `parser`。

**Comment by cloydlau** [comment]
知道了，`modelValue` 的值类型在 `text` 模式下必须为字符串，需要 JSON.stringify 一下（如果有 bigint，可以使用 lossless-json 来 stringify）。再一次说明最小可复现链接是非常有必要的，否则维护者会受到误导。

**Comment by cloydlau** [comment]
文档已更新，`modalValue` 的类型现在对不同模式进行了区分。

**Comment by cloydlau** [comment]
跟作者讨论了一下，原文档中说的 text 模式只接受字符串是有误的，在 `json-editor-vue@0.7.2` 中已支持在 text 模式下直接传入 JSON。

**Comment by comxza** [comment]
谢谢大佬的回复，
