### ISSUE TITLE
How to read a raw string from Content?

### ISSUE THREAD

**Issue by jtuchel** [cloydlau/json-editor-vue#17]
Hey there,
thank you very much for the effort. I want to use your component by passing in the current content as a prop and emit the modified string back to its parent.

```vue
<script setup lang="ts">
import JsonEditorVue, { Mode } from "json-editor-vue";
import type { Content, ContentErrors, JSONPatchResult } from "vanilla-jsoneditor";
import { type Ref, ref } from "vue";

defineProps<{ content: string; }>();

const emit = defineEmits<{ (e: "update:content", content: string): void; }>();

function onChange(content: Content, previousContent: Content, changeStatus: { contentErrors: ContentErrors; patchResult: JSONPatchResult | null; }): void {
  // get a raw string from content
  const newContent: string = "raw content string";

  emit("update:content", newContent);
}
</script>

<template>
  <json-editor-vue :value="content" @change="onChange" />
</template>
```

How can I read a raw string from the `content` variable? Is it possible to get it without any escape characters?

I want to validate and parse the raw string later on :)

**Comment by cloydlau** [comment]
Hello,

```html
<JsonEditorVue
  :onChange="(updatedContent, previousContent, { contentErrors, patchResult }) => {
    // Firstly you can listen every event of vanilla-jsoneditor
  }"
  @update:modelValue="value => {
    // 'value' is exactly what vanilla-jsoneditor returns
    // (`updatedContent.text` or `updatedContent.json`)
  }"
/>
```

I'm not sure what do you mean by 'raw string' though.

**Comment by jtuchel** [comment]
@cloydlau thanks a lot for your reply!

I think `updatedContent.text` is what I'm looking for. But I'm using TypeScript so the compiler doesn't know the `text` property because it doesn't know if `updatedContent` is of type `JSONContent | TextContent`. Do you know how to read the `text` property from it?

**Comment by cloydlau** [comment]
I'm not sure what is your problem, could you be more specified about what's preventing you from reading the `text` property?

**Comment by cloydlau** [comment]
A codesandbox reproduction will be great!

**Comment by jtuchel** [comment]
> I'm not sure what is your problem, could you be more specified about what's preventing you from reading the `text` property?

Sure :) Starting with the following code

```ts
function onChange(updatedContent: Content, previousContent: Content, changeStatus: { contentErrors: ContentErrors; patchResult: JSONPatchResult | null; }): void {
  console.log(updatedContent.text); // TS2339: Property 'text' does not exist on type 'Content'. Property 'text' does not exist on type '{ json: JSONValue; }'.
}
```

I get the error because the TS compiler doesn't know if the text property exists. Because `updatedContent` might be of type `JSONContent`

**Comment by cloydlau** [comment]
```ts
import type { TextContent } from 'vanilla-jsoneditor'

console.log((updatedContent as TextContent).text)
```
