### ISSUE TITLE
v-model doesn't work when :onChange is used

### ISSUE THREAD

**Issue by RoboVij** [cloydlau/json-editor-vue#19]
I'm trying to access `contentErrors` through `:onChange`. Without `:onChange` `v-model` binds the value to the prop I gave (which is a computed value, an object ). But with `:onChange` it doesn't. I checked the issues #17 #18 but I'm not able to implement it properly. 

I'm using  `"vue": "^2.6.11"`

My main goal is to not accept the value when there are errors in it (`text` mode) i.e. there's an ACCEPT button which gets disabled. Or instead of `:onChange` is there any other alternative? Like `:onError`, but it's not working. I guess it serves a different purpose.

```javascript
<JsonEditorVue 
   v-model="deviceCurated.properties" 
   :mode.sync="text"
   :class="$vuetify.theme.dark ? 'jse-theme-dark' : ''"
   :mainMenuBar="false"
   :onChange="(updatedContent, previousContent, { contentErrors }) => {jsonChange(updatedContent, contentErrors)}"
 />


  get deviceCurated(): any {
    return { properties: {} };
  }

  jsonChange(updatedContent: TextContent, contentErrors: ContentErrors) {
    console.log(this.deviceCurated.properties);
    // console.log(updatedContent.text);
    Object.keys(contentErrors).forEach((e: string) => {
      if(e === 'validationErrors') this.isJsonError = false;
      if(e === 'parseError') this.isJsonError = true;
    })
  }
```

Also after editing the value (when v-model works), instead of an object/json, it's giving a string (maybe because of `text` mode). So I'm doing `JSON.parse()`. Is there a better way?

**Comment by cloydlau** [comment]
It seems a bug of `vue-global-config`, I will fix it tomorrow. (UTC+8 here)

**Comment by cloydlau** [comment]
Fixed in v0.9.1.

> Also after editing the value (when v-model works), instead of an object/json, it's giving a string (maybe because of text mode). So I'm doing JSON.parse(). Is there a better way?

Content in text mode may be invalid JSON. So it's probably not applicable for `json-editor-vue` to do `JSON.parse`.

**Comment by RoboVij** [comment]
For some reason, it won't install

```javascript
npm ERR! code ETARGET
npm ERR! notarget No matching version found for json-editor-vue@^0.9.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

I tried `npm i json-editor-vue@0.9.1`, `npm update json-editor-vue`, `npm install json-editor-vue --legacy-peer-deps`, `npm update json-editor-vue --legacy-peer-deps`, deleted `package-lock.json`, `npm cache clean --force`.

Previously I installed (`json-editor-vue: 0.8.0`) with `npm install json-editor-vue --legacy-peer-deps` since there was an error saying mismatching about vue versions. This time also there's an error `npm WARN EBADENGINE Unsupported engine`. I was using `node: 14.6.0` but it needs `16+` so I upgraded to `node: 16.7.1`. But now the above error persists

**Comment by cloydlau** [comment]
It should be your npm registry or network problem. Hit https://www.npmjs.com/package/json-editor-vue/v/0.9.1. Delete your npm registry.

**Comment by RoboVij** [comment]
It's working now. Thanks for your quick work/responses

**Comment by cloydlau** [comment]
You're welcome. A Star will be helpful thanks.
