### ISSUE TITLE
schema validate

### ISSUE THREAD

**Issue by ArnurArykbaev** [cloydlau/json-editor-vue#26]
I would like to use with a schema. Can you tell me if this is possible, and if so, how?

**Comment by cloydlau** [comment]
What do you use that for? Validation?
```html
<JsonEditorVue :validator="customValidator" />
```
Implementation of `customValidator` see https://github.com/josdejong/svelte-jsoneditor/blob/main/src/routes/examples/custom_validation/%2Bpage.svelte

**Comment by ArnurArykbaev** [comment]
Thank you! Your answer helped me!

It was necessary to connect json-schema-validator and pass to the data validator property with createAjvValidator and called to it in :validator
example: maybe it will help someone in future
`
          <JsonEditorVue
            :validator="validator"
            v-model="jsonContract"
            @change="changed(contract)"
          />

<script>
import { createAjvValidator } from "vanilla-jsoneditor";
import schema from "./../schema/schemToValidate.json";

data: () => ({
    validator: createAjvValidator({
      schema,
      schemaDefinitions: {},
      ajvOptions: {
        strict: false,
      },
`

**Comment by cloydlau** [comment]
You're welcome. A Star will be helpful thanks.
