### ISSUE TITLE
在Vue 2.6版本中使用报错

### ISSUE THREAD

**Issue by hehanli101** [cloydlau/json-editor-vue#28]
项目中使用了inject
全局注册json-editor-vue

控制台报错
 inject() can only be used inside setup() or functional components.

**Comment by cloydlau** [comment]
![image](https://user-images.githubusercontent.com/31238760/205838804-e6d65aee-5025-46bf-8afb-fd42afe3a174.png)

你好，无法复现该问题，请提供[最小化可复现的 codesandbox](https://codesandbox.io)。
> [为什么最小化可复现是必要的](https://antfu.me/posts/why-reproductions-are-required)

**Comment by hehanli101** [comment]
> ![image](https://user-images.githubusercontent.com/31238760/205838804-e6d65aee-5025-46bf-8afb-fd42afe3a174.png)
> 
> 你好，无法复现该问题，请提供最小化可复现的 [CodeSandbox](https://codesandbox.io)，谢谢。
> 
> > [为什么复现是必要的](https://antfu.me/posts/why-reproductions-are-required-zh)

我弄错了 不是这个问题 ，项目中使用了vue-echarts ，我单独引入@vue/composition-api 报错了，和这个组件本身没关系
