### ISSUE TITLE
js文件报文件不支持？

### ISSUE THREAD

**Issue by qishibo** [cloydlau/json-editor-vue#3]
是我的svelte环境有问题么，通过`import { JSONEditor } from 'svelte-jsoneditor/dist/jsoneditor.js'`加载js文件时总报类型不支持
```
Failed to compile.

./node_modules/svelte-jsoneditor/dist/jsoneditor.js
Module parse failed: Unexpected token (5:23414)
You may need an appropriate loader to handle this file type.
|  * Font Awesome Free 5.15.4 by @fontawesome - https://fontawesome.com
|  * License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)
|  */var Pe={prefix:"fas",iconName:"angle-down",icon:[320,512,[],"f107","M143 352.3L7 216.3c-9.4-
```

**Comment by cloydlau** [comment]
你好，json-editor-vue是在vue里面用的，svelte-jsoneditor只是一个外置依赖，无需引入，如果是svelte环境，使用svelte-jsoneditor就可以

**Comment by qishibo** [comment]
坑在这，在vue里得指定用babel-loader加载svelte-jsoneditor

**Comment by zjh0x** [comment]
我也碰到这个问题，咋解决的啊？

**Comment by cloydlau** [comment]
请提供最小可复现 codesandbox 链接

**Comment by azxhwang** [comment]
> 你好，json-editor-vue是在vue里面用的，svelte-jsoneditor只是一个外置依赖，无需引入，如果是svelte环境，使用svelte-jsoneditor就可以

不引入svelte-jsoneditor，编译时会报错：This dependency was not found:
* svelte-jsoneditor/dist/jsoneditor.js in ./node_modules/json-editor-vue/dist/json-editor-vue.umd.js。
环境是Vue 2.6
