### ISSUE TITLE
Prop type / Event type does not appear

### ISSUE THREAD

**Issue by xhayper** [cloydlau/json-editor-vue#33]
<img width="485" alt="Screenshot 2022-12-19 at 08 25 13" src="https://user-images.githubusercontent.com/46065349/208330711-d23aa47c-26fa-4c88-bbfd-313e029bdf88.png">

On the bright side,
Auto import on nuxt 3 works.
The component correctly give out div's type.

**Comment by cloydlau** [comment]
Hello. I can't reproduce this:

![image](https://user-images.githubusercontent.com/31238760/208346005-a1d1a304-752c-41e2-b8ff-90291e1b88a3.png)

![image](https://user-images.githubusercontent.com/31238760/208346041-2e8adcb2-9656-446c-9d14-d1bded8fbae3.png)

How can we tell this isn't related to VSCode or tsconfig.json?

**Comment by xhayper** [comment]
I will test it again later today on my main pc

**Comment by xhayper** [comment]
Seems to be bug with volar, sorry!
