### ISSUE TITLE
 Can't load the plugin

### ISSUE THREAD

**Issue by apertureless** [cloydlau/json-editor-vue#34]
Hey, I have an older vue-cli project, however with vue 2.7 
After installation and trying to globally register the plugin I am getting following errors

```bash
error  in ./node_modules/json-editor-vue/dist/json-editor-vue.mjs

Module parse failed: Unexpected token (205:16)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| function Ft(t, r) {
|   var n = typeof t;
>   return r = r ?? se, !!r && (n == "number" || n != "symbol" && le.test(t)) && t > -1 && t % 1 == 0 && t < r;
| }
| function lt(t, r, n) {

 @ ./src/main.ts 26:0-44 27:8-21
```

I tried to add a rule for mjs files to my vue.config.js

```js
 chainWebpack: config => {
    config.module
        .rule('mjs$')
        .test(/\.mjs$/)
        .include
            .add(/node_modules/)
            .end()
        .type('javascript/auto')
  },
```

but this also do not work.

**Comment by cloydlau** [comment]
Hello.
What's your `vue-cli` version? Will upgrading to `4.5.19` solve your problem? If not, a codesandbox link will be helpful.

**Comment by apertureless** [comment]
My `vue-cli` version is `4.5.13` I've upgraded to 4.5.19 but the same. Also tried to upgrade to the latest (5.0.8) but the same.

Gonna see if I can create a codesandbox. Its a yeoman generated project with a lot of internal / non-public dependencies.

**Comment by cloydlau** [comment]
I managed to create a reproduction, working on it.

**Comment by cloydlau** [comment]
This problem comes with the nullish coalescing operator — `??`

**Comment by cloydlau** [comment]
Vite 4 (Rollup 3) uses ES2020 for compiler target by default so `?.` and `??` won't be transformed anymore when building.
Which should not be a problem because Vue CLI already supports `?.` or `??`, just not for 'node_modules' packages.
`transpileDependencies` is born for this but actually not working:
```js
// vue.config.js
module.export = {
  transpileDependencies: ['json-editor-vue'],
}
```
So figuring out how to transform `?.` or `??` for 'node_modules' packages in Vue CLI should be a proper solution.
Or you can temporarily use version `0.10.4` (built with Vite 3).

**Comment by cloydlau** [comment]
In Vue CLI 5:
Ready to use right out of the box.
[Vue CLI 5 Demo](https://github.com/cloydlau/json-editor-vue/tree/main/demo/vue-cli5)

In Vue CLI 4:
Vite 4 (Rollup 3) uses ES2020 as compiler target by default, therefore Vite-4-built outputs should be transpiled in webpack 4.
```js
// vue.config.js
module.exports = {
  transpileDependencies: ['json-editor-vue'],
}
```
[Vue CLI 4 Demo](https://github.com/cloydlau/json-editor-vue/tree/main/demo/vue-cli4)

**Comment by cloydlau** [comment]
Please feel free to reach out to me if you have any further question.

**Comment by janhaa** [comment]
For reference, solved in nuxt 2 by adding in nuxt.config.js:
`
build: {
    transpile: [
        'json-editor-vue'
    ],
    extend (config) {
        config.module.rules.push({
            test: /\.mjs$/,
            include: /node_modules/,
            type: 'javascript/auto'
        })
    }
}
`

**Comment by cloydlau** [comment]
> For reference, solved in nuxt 2 by adding in nuxt.config.js:
> 
> ```
> build: {
>     transpile: [
>         'json-editor-vue'
>     ],
>     extend (config) {
>         config.module.rules.push({
>             test: /\.mjs$/,
>             include: /node_modules/,
>             type: 'javascript/auto'
>         })
>     }
> }
> ```

Good work. `transpile: ['json-editor-vue']` has been added to the document.
