### ISSUE TITLE
Using with Nuxt3

### ISSUE THREAD

**Issue by andyjamesn** [cloydlau/json-editor-vue#4]
I am trying to test this with Nuxt 3 and I am getting document is not defined when the page loads.

I have tried using the transpile settings in the nuxt config and <ClientOnly> wrapped around the plugin but no luck.

Any ides how I could get this working?

**Comment by cloydlau** [comment]
I think it's not related to `json-editor-vue`, check https://stackoverflow.com/questions/46058544/document-is-not-defined-in-nuxt-js .

**Comment by andyjamesn** [comment]
Hello. 

Yes this thread is about the topic at hand but it is referring to Nuxt 2 not Nuxt 3.

Essentially Nuxt loads from the server side since its server side rendering so the document is not available at time of compiling. 

The thread posted highlights solutions to make a plugin run in the client only however this is a little different in Nuxt3

The bottom line is that none of the solutions to make json-editor-vue work in Nuxt 3 on the client side do not work which is strange as I have done this with many other plugins that also require the document and usually the solutions like transpile or client-only work.

So as it stands this plugin seems incompatible with Nuxt3 unless I am missing something.

**Comment by cloydlau** [comment]
I can reproduce this with [svelte-jsoneditor](https://github.com/josdejong/svelte-jsoneditor) in nuxt 3 with the codes below:

```vue
<template>
  <client-only>
    <div id="JSONEditor" />
  </client-only>
</template>

<script setup>
import { JSONEditor } from 'svelte-jsoneditor/dist/jsoneditor.js'
import { onMounted } from 'vue'

onMounted(() => {
  new JSONEditor({
    target: document.querySelector('#JSONEditor'),
  })
})
</script>

```

And another lib has the same problem: https://stackoverflow.com/questions/71484930/using-aos-with-nuxt3. 

So it's not necessarily an issue of svelte-jsoneditor.

My suggestion is opening an issue to svelte-jsoneditor or nuxt 3 with minimal reproducible example.

**Comment by cloydlau** [comment]
Usage with nuxt 2 / 3 is now been documented.
