### ISSUE TITLE
可以设置语言的么，想设置中文语言。

### ISSUE THREAD

**Issue by FreezeJ** [cloydlau/json-editor-vue#58]
我看了[svelte-jsoneditor](https://github.com/josdejong/svelte-jsoneditor)的参数，好像并没有设置语言的字段。请教一下，可以把菜单按钮设置为中文么？
在[jsoneditor](https://github.com/josdejong/jsoneditor)中是提供了i18n，可以设置中文的，但是功能又没有那么多。

**Comment by cloydlau** [comment]
你好，提 issue 前先看了两篇文档，先给你点一个赞，能做到人并不多。
我也去 svelte-jsoneditor 的 issue 区搜索了一下，确实居然没人提这个问题。
我想是因为 JSON 的编辑通常只有开发者会使用，并不是面向普通用户的，所以 i18n 的需求并不高。
不过当然，i18n 是有用的，只是这肯定超越了 Vue Wrapper 的范畴，建议你将这个 issue 转移到 svelte-jsoneditor，看看作者怎么说。

**Comment by cloydlau** [comment]
如果急用的话，也许可以从「翻译 DOM 元素中的英文」这个角度入手，有没有什么库或者办法可以做到类似右键「翻译成中文」的功能。

**Comment by FreezeJ** [comment]
感谢回复，原作者在一个issues中提到，大概意思应该是：“如果做i18n，其它语言版本可能跟不上更新。”

我从[svelte-jsoneditor](https://github.com/josdejong/svelte-jsoneditor) fork了一份到自己的仓库[svelte-jsoneditor](https://github.com/FreezeJ/svelte-jsoneditor)并做了一些菜单的汉化，纯手改的可能有些翻译不到位，有需要的可以拉一份重新编译。
![](https://raw.githubusercontent.com/FreezeJ/svelte-jsoneditor/main/misc/1.png)

**Comment by cloydlau** [comment]
你是说中文文档那个？中文文档的话确实存在这个问题，不可能要求作者去维护这份文档。不过 i18n 是一种能力，要让用户能够方便地替换文本，至于替换成什么由用户自己维护，甚至顺带实现了「自定义文案」，还是值得做的。
