### ISSUE TITLE
"Edit the Selected Path" breaks with Error : (Uncaught (in promise) TypeError: c6.stringify is not a function)

### ISSUE THREAD

**Issue by feidhlimx** [cloydlau/json-editor-vue#59]
$ npm list
├── @ts-pro/vue-eternal-loading@1.3.0
├── @types/jsdom@20.0.1
├── @types/node@18.11.18
├── @vitejs/plugin-vue-jsx@3.0.0
├── @vitejs/plugin-vue@4.0.0
├── @vue/test-utils@2.2.8
├── @vue/tsconfig@0.1.3
├── @vueform/toggle@2.1.3
├── @vueuse/core@9.11.1
...
├── json-editor-vue@0.10.5
├── postcss@8.4.21
├── tailwindcss@3.2.4
├── typescript@4.9.4
├── vanilla-jsoneditor@0.14.3
├── vite@4.0.4
├── vue-router@4.1.6
├── vue-tsc@1.0.24
└── vue@3.2.45
...

Click on "Edit the selected Path" to reproduce the error - which occurs in the file:
/node_modules/src/lib/components/controls/navigationBar/NavigationBarPathEditor.svelte

 (Uncaught (in promise) TypeError: c6.stringify is not a function)

![image](https://user-images.githubusercontent.com/107552740/215130048-5b13d0a9-cf4b-4f37-953c-4142ec55a4e3.png)

**Comment by cloydlau** [comment]
I tried but could not reproduce this. Please provide a minimal reproduction via a github repo or codesandbox so I can locate it thanks.

**Comment by cloydlau** [comment]
👇 json-editor-vue@0.10.5 + vanilla-jsoneditor@0.14.3

![chrome_bZAqF8pvi1](https://user-images.githubusercontent.com/31238760/215270771-87eaf7d8-4718-4d83-ace6-dc354915ca77.gif)

**Comment by feidhlimx** [comment]
Sorry, my problem, was trying to use pathParser - incorrectly.
