### ISSUE TITLE
时间类型添加秒级时间戳的识别

### ISSUE THREAD

**Issue by SeigeC** [cloydlau/json-editor-vue#6]
![image](https://user-images.githubusercontent.com/39756973/188412800-584c6da9-dc4f-46e6-ad2e-e322e1f4d6ec.png)

**Comment by cloydlau** [comment]
一个低于13位的数字，要怎么知道它是一个单纯的数字还是一个时间戳呢？

**Comment by SeigeC** [comment]
对于 13 位的数字就当做时间戳就好了，反正就算不是时间戳看起来也没有影响正常的显示

**Comment by cloydlau** [comment]
请描述清楚你的需求，什么叫“秒级时间戳”？现在的逻辑就是 [13, 16] 位数字会被认为是时间戳，其他长度的数字被认为是数字。这个逻辑有什么问题吗？
