### ISSUE TITLE
ReferenceError: require is not defined

### ISSUE THREAD

**Issue by sean8601** [cloydlau/json-editor-vue#60]
原来遇到了一个编译失败问题，通过以下方法解决了：
npm i @babel/plugin-proposal-nullish-coalescing-operator @babel/plugin-proposal-optional-chaining -D
// babel.config.js

module.exports = {
  plugins: [
    '@babel/plugin-proposal-nullish-coalescing-operator',
    '@babel/plugin-proposal-optional-chaining',
  ],
}
// vue.config.js

module.exports = {
  transpileDependencies: ['json-editor-vue'],
  chainWebpack(config) {
    // Getting webpack to recognize the `.mjs` file
    config.module
      .rule('mjs')
      .include.add(/node_modules/)
      .type('javascript/auto')
      .end()
  },
}

然后，页面抛了一个异常：
ReferenceError: require is not defined
  at ./node_modules/json-editor-vue/dist/json-editor-vue.mjs(jso-editor-vue.mjs:3:1)
  ...
版本信息如下：
vue：2.6.10
node：8.9.0
请教大佬这个异常需要怎么解决呢？谢谢！

**Comment by cloydlau** [comment]
你好，能提供下最小化可复现的 github/codesandbox 链接吗，我才好定位你的问题。

**Comment by cloydlau** [comment]
vue-cli 3 demo: https://github.com/cloydlau/json-editor-vue/tree/main/demo/vue-cli3
该 demo 经测试：
1. 使用 node 12.22.12 + npm + vue 2.7.14，可以正常运行；
2. 使用 node 8.9.0 + npm + vue 2.6.10，可以正常运行。
