### ISSUE TITLE
Usage on Vue 2.6

### ISSUE THREAD

**Issue by azxhwang** [cloydlau/json-editor-vue#64]
<img width="1122" alt="image" src="https://user-images.githubusercontent.com/26570647/220558356-f3c176ed-917e-4b39-a3eb-42e812d2d5f4.png">
I use followings to install package:
yarn add json-editor-vue vanilla-jsoneditor @vue/composition-api

**Comment by cloydlau** [comment]
Hello, I tried using yarn to install dependecies in this [Vue 2.6 demo](https://github.com/cloydlau/json-editor-vue/tree/main/demo/vue2.6) but everything went well.
So please provide a minimal reproduction to reopen this issue, so that I can look into your problem, appreciated!
