### ISSUE TITLE
Text mode cursor and selection are not showing

### ISSUE THREAD

**Issue by w-A-L-L-e** [cloydlau/json-editor-vue#66]
Editor works in table mode. But in text mode you can edit the text but the cursor is not visible (no blinking cursor).
Also you can highlight and then remove but you do not see you highlighted text:

```
  <JsonEditorVue
        v-model="sip_schema"
        mode="table"
        :readOnly="false"
      />

```

in package.json:
```
    "json-editor-vue": "^0.10.5",
    "vanilla-jsoneditor": "^0.15.1",
```

Using     "vue": "^3.2.41",
and vite for minify (but issue is present both in development npm run dev and in production mode).
When on a line you do see it highlighted but you can't select part or multiple lines and see the dark selected text like you can on https://jsoneditoronline.org/

**Comment by w-A-L-L-e** [comment]
When double clicking some weird selection is made sometimes (and its not in the place where you clicked):

![Screenshot 2023-03-14 at 17 32 31](https://user-images.githubusercontent.com/710803/225086474-19f2bf86-2a49-441c-8030-ad2f7e72e954.png)

**Comment by cloydlau** [comment]
I can't reproduce your problem on https://cloydlau.github.io/demo/json-editor-vue.html (a minimal json-editor-vue demo, using Vue 3 too).
This could due to external reasons like browser plugins.
Please provide a minimal reproduction so that I can look into this, thanks.
