### ISSUE TITLE
Edit Main Menu

### ISSUE THREAD

**Issue by Goksel12211** [cloydlau/json-editor-vue#69]
![image](https://github.com/cloydlau/json-editor-vue/assets/77725216/9c053894-416f-43d8-a7f2-a4e5cc1c371a)
How i can edit MainMenu ? For example : I don't want to remove table option , change color and search button . Is there any solution using props for this ?

**Comment by cloydlau** [comment]
![image](https://github.com/cloydlau/json-editor-vue/assets/31238760/f4525365-6024-4810-ab86-5e0f24337956)

Since you have already read the [doc](https://github.com/josdejong/svelte-jsoneditor#readme), you should know whether there are props for that or not.

**Comment by cloydlau** [comment]
What are the advantages of creating countless props instead of using CSS?

**Comment by cloydlau** [comment]
You can create a PR to svelte-jsoneditor, it would certainly be nice to customize the menu in a treeshakable way.
