### ISSUE TITLE
在chrome浏览器下，http时复制会报TypeError: Cannot read properties of undefined (reading 'writeText')

### ISSUE THREAD

**Issue by yimouren** [cloydlau/json-editor-vue#8]
经查询是chrome在http时navigator.clipboard会undefined，希望可以添加兼容的写法

**Comment by cloydlau** [comment]
我提了一个 [PR](https://github.com/josdejong/svelte-jsoneditor/pull/144) 给 `svelte-jsoneditor`，可以解决这个问题，还提升了浏览器兼容性，看作者给不给合了。

**Comment by yimouren** [comment]
你好，你的邮件我已经收到，将会尽快处理，谢谢。

**Comment by yimouren** [comment]
谢谢老哥

**Comment by cloydlau** [comment]
PR 已被合并，升级 `vanilla-jsoneditor` 到 `0.7.5` 即可

**Comment by yimouren** [comment]
star star！
