### ISSUE TITLE
初始expand的深度

### ISSUE THREAD

**Issue by liushuaikobe** [cloydlau/json-editor-vue#9]
请问有没有办法可以指定编辑器在 readonly 模式下的初始化展示 JSON 的 深度？

**Comment by cloydlau** [comment]
JSON 的深度跟模式有关系吗？我试了一下现在不是默认全展开的吗，你想要什么效果？比如10层的深度，你想要指定展开第5层这种？试试 `expand`, `scrollTo` 能否满足你的需求。

**Comment by cloydlau** [comment]
先暂时关闭了，如有疑问随时打开。

**Comment by liushuaikobe** [comment]
我设置了 组件的 `ref` 如下（组件是在 `v-for` 内，理论上应该会有很多实例）
![image](https://user-images.githubusercontent.com/2098020/191930568-c17e28c5-569f-4db1-91f3-2d8407122829.png)

然后在 `mounted` 中通过 `ref` 引用获取不到组件实例，是个 Proxy 对象，如下。
![image](https://user-images.githubusercontent.com/2098020/191932548-2cd766b4-d28b-4a25-8aab-fcba3fa06936.png)

![image](https://user-images.githubusercontent.com/2098020/191932769-88540851-6dce-4c7c-a2ba-fc67ab46d059.png)

对其直接调用方法报错。

麻烦谅解，我不是专业的前端，如造成困扰，很抱歉。

**Comment by cloydlau** [comment]
首先在循环里面 ref 命名怎么能写死呢，那不就重复了吗，ref 得写成动态的，比如 `:ref="'jsonEditorVue' + i"`，这个算 Vue 基础了。

想要调用 svelte-jsoneditor 的方法，第一步要获取 svelte-jsoneditor 的实例对象。这个在文档里是写了的：

![image](https://user-images.githubusercontent.com/31238760/191936163-6a3fef38-da92-4bf8-8193-126c6ead6369.png)

最后代码是这样的：

- `jsonEditorVue0.value.jsonEditor.expand()`
- `jsonEditorVue0.value.jsonEditor.scrollTo()`

有点长但是逻辑非常清晰：

- `jsonEditorVue0.value` 这个是你定义的 ref，为什么加 `.value` 我就不解释了吧，这个也属于 Vue 基础范畴
- `jsonEditorVue0.value.jsonEditor` 这个是 svelte-jsoneditor 的实例对象

**Comment by cloydlau** [comment]
你这也没说 Vue 版本，我看了一下，2.6 的话确实没有暴露  `jsonEditor`，会立即修复。

**Comment by cloydlau** [comment]
你这也没说 Vue 版本，如果你用的是选项式 API，这么拿：`this.$refs.jsonEditorVue0.jsonEditor.expand`
**（需要升级到 `v0.6.6` ）**
