### ISSUE TITLE
Unintentional scrolling in text mode

### ISSUE THREAD

**Issue by lbertoncello** [cloydlau/json-editor-vue#95]
### Before you start, please make sure to:

- [X] Read the document
- [X] Have tried the latest version
- [X] Search to see if your issue already exists

### Link to minimal reproduction

https://codesandbox.io/p/sandbox/json-editor-vue-issue-hfjrsd

### Validation

- [X] ⚠️ I understand that invalid, incomplete or superfluous reproduction can lead to this issue being closed

### Describe the bug and steps to reproduce

I have noticed that every time the component is mounted the page is automatically scrolled to it. This is only happens if `mode === Mode.text`.

You can check this behaviour in the codebox I linked. Note that every time you click on the button to display the component, the page is scrolled all the way to it.

I have searched about both `json-web-editor` and `svelte-jsoneditor`, but I couldn't find any issue related to this. That being said, I would like to know if this is a intentional behaviour? If so, is there a way to disable this scrolling?

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 13th Gen Intel(R) Core(TM) i5-13450HX
    Memory: 5.12 GB / 23.69 GB
  Binaries:
    Node: 20.11.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (126.0.2592.113)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @aws-sdk/client-s3: ^3.556.0 => 3.614.0
    @aws-sdk/lib-storage: ^3.554.0 => 3.614.0
    @nuxt/eslint-config: ^0.2.0 => 0.2.0
    @nuxt/image: ^1.3.0 => 1.7.0
    @nuxt/types: ^2.17.3 => 2.18.1
    @nuxt/typescript-build: ^3.0.2 => 3.0.2
    @nuxtjs/color-mode: ^3.3.2 => 3.4.2
    @nuxtjs/eslint-config-typescript: ^12.1.0 => 12.1.0
    @nuxtjs/eslint-module: ^4.1.0 => 4.1.0
    @nuxtjs/tailwindcss: ^6.11.3 => 6.12.1
    @pinia-plugin-persistedstate/nuxt: ^1.2.0 => 1.2.1
    @pinia/nuxt: ^0.5.1 => 0.5.1
    @prisma/client: ^5.9.1 => 5.16.2
    @tailwindcss/forms: ^0.5.7 => 0.5.7
    @tiptap/extension-link: ^2.2.4 => 2.5.0
    @tiptap/extension-underline: ^2.2.3 => 2.5.0
    @tiptap/pm: ^2.2.3 => 2.5.0
    @tiptap/starter-kit: ^2.2.3 => 2.5.0
    @tiptap/vue-3: ^2.2.3 => 2.5.0
    @typescript-eslint/parser: ^6.21.0 => 6.21.0
    @vee-validate/nuxt: ^4.12.5 => 4.13.2
    @vee-validate/yup: ^4.12.5 => 4.13.2
    @vueuse/components: ^10.9.0 => 10.11.0
    @vueuse/integrations: ^10.10.0 => 10.11.0
    @vueuse/nuxt: ^10.7.2 => 10.11.0
    eslint: ^8.56.0 => 8.57.0
    eslint-config-prettier: ^9.1.0 => 9.1.0
    eslint-plugin-prettier: ^5.1.3 => 5.1.3
    json-editor-vue: ^0.15.1 => 0.15.1
    nuxt: ^3.10.1 => 3.12.3
    nuxt-lucide-icons: ^1.0.4 => 1.0.5
    nuxt-security: ^2.0.0-rc.6 => 2.0.0-rc.9
    nuxt-tiptap-editor: ^1.1.0 => 1.1.2
    pinia: ^2.1.7 => 2.1.7
    prettier: ^3.2.5 => 3.3.3
    prisma: ^5.9.1 => 5.16.2
    sharp: ^0.33.4 => 0.33.4
    sortablejs: ^1 => 1.15.2
    vite: ^5.1.6 => 5.3.3
    vue: ^3.4.15 => 3.4.31
    vue-router: ^4.2.5 => 4.4.0
    yup: ^1.3.3 => 1.4.0
```

### Package Manager

npm

**Comment by cloydlau** [comment]
This is a bug in the upstream dependency. I have opened https://github.com/josdejong/svelte-jsoneditor/pull/471 to track this.

**Comment by cloydlau** [comment]
@lbertoncello vanilla-jsoneditor@0.23.8 had just landed for this.
1. `npm r json-editor-vue`
2. `npm i json-editor-vue`
3. Check if the version of `vanilla-jsoneditor` in `node_modules` is upgraded to 0.23.8

**Comment by lbertoncello** [comment]
@cloydlau This new version has solved my issue. Thank you very much!

**Comment by cloydlau** [comment]
You're welcome. You can support this project by giving it a Star~

**Comment by lbertoncello** [comment]
> You're welcome. You can support this project by giving it a Star~

@cloydlau No problem, it's done
