### ISSUE TITLE
Custom Rendering

### ISSUE THREAD

**Issue by mmadson** [cloydlau/json-editor-vue#97]
### Before you start, please make sure to:

- [X] Read the document
- [X] Have tried the latest version
- [X] Search to see if your proposal already exists

### What problem does this feature solve?

I'd like to mark certain json properties as sensitive so that their value is hidden with some kind of eye icon until the user clicks the icon to reveal the value. 

### What does the proposed API look like?

I'm not sure if this can be accomplished using the svelte properties. An example of supplying custom property / value renderers would be very helpful.

**Comment by cloydlau** [comment]
I think it's described in the document: https://github.com/josdejong/svelte-jsoneditor?tab=readme-ov-file#onrendervalue

---

Please consider starring ⭐ to support our ongoing maintenance if you find it useful or your proposal was resolved afterwards.
